### ISSUE TITLE
Optimizations for benchmarks or real cases?

### ISSUE THREAD

**Issue by zerkalica** [infernojs/uibench-inferno#1]
In real applications we use only one way to create component instance: jsx.

You mix createVNode and direct component calling:
Fairly to use jsx and createVNode everywhere.

```js

	if (location === 'table') {
		section = table(data.table);
	} else if (location === 'anim') {
		section = anim(data.anim);
	} else if (location === 'tree') {
		section = tree(data.tree);
	}

```

**Comment by trueadm** [comment]
@zerkalica These aren't components, just functions. I don't think this benchmark implementation even uses components actually. There's another implementation that uses components in the `react-like` directory.

**Comment by zerkalica** [comment]
But what for first benchmark? If compare with react-like Main, it looks like some technical trick. What is the case, when we need to do same in real application?

**Comment by trueadm** [comment]
@zerkalica This benchmark isn't meant to be like a real application though – it's meant to stress the internals. Using these benchmarks is pointless for comparing to real-world apps because no one builds apps full up huge tables, nested lists and spinning animated divs. Also, JSX compiles to `createVNode`, so what you see in the benchmark is completely do-able with JSX too.

**Comment by Havunen** [comment]
uiBench is mainly used for regression tracking in different areas of performance

**Comment by zerkalica** [comment]
Ok, thanks.
